var ru_en = {
	"Восточная конференция": "Eastern Conference",
	"Западная конференция": "Western Conference",
	"Дивизион Метраполитан": "Metropolitan Division",
	"Атлантический дивизион": "Atlantic Division",
	"Центральный дивизион": "Central Division",
	"Тихоокеанский дивизион": "Pacific Division",
	"Cделано с": "Made with",
	"к хоккею": "to hockey",

	"Каролина": "Carolina",
	"Харрикейнз": "Hurricanes",
	"Коламбус": "Columbus",
	"Блю Джекетс": "Blue Jackets",
	"Нью-Джерси": "New Jersey",
	"Девилз": "Devils",
	"Нью-Йорк": "New York",
	"Айлендерс": "Islanders",
	"Рейнджерс": "Rangers",
	"Филадельфия": "Philadelphia",
	"Флайерз": "Flyers",
	"Питтсбург": "Pittsburgh",
	"Пингвинз": "Penguins",
	"Вашингтон": "Washington",
	"Кэпиталз": "Capitals",

	"Бостон": "Boston",
	"Брюинз": "Bruins",
	"Баффало": "Buffalo",
	"Сэйбрз": "Sabres",
	"Детройт": "Detroit",
	"Ред Уингз": "Red Wings",
	"Флорида": "Florida",
	"Пэнтерз": "Panthers",
	"Монреаль": "Montreal",
	"Канадиенс": "Canadiens",
	"Оттава": "Ottawa",
	"Сенаторз": "Senators",
	"Тампа-Бэй": "Tampa Bay",
	"Лайтнинг": "Lightning",
	"Торонто": "Toronto",
	"Мэйпл Лифс": "Maple Leafs",

	"Чикаго": "Chicago",
	"Блэкхокс": "Blackhawks",
	"Колорадо": "Colorado",
	"Эвеланш": "Avalanche",
	"Даллас": "Dallas",
	"Старз": "Stars",
	"Миннесота": "Minnesota",
	"Уайлд": "Wild",
	"Нэшвилл": "Nashville",
	"Предаторз": "Predators",
	"Сент-Луис": "St. Louis",
	"Блюз": "Blues",
	"Виннипег": "Winnipeg",
	"Джетс": "Jets",

	"Анахайм": "Anaheim",
	"Дакс": "Ducks",
	"Аризона": "Arizona",
	"Койотиз": "Coyotes",
	"Калгари": "Calgary",
	"Флэймз": "Flames",
	"Эдмонтон": "Edmonton",
	"Ойлерз": "Oilers",
	"Лос-Анджелес": "Los Angeles",
	"Кингз": "Kings",
	"Сан-Хосе": "San Jose",
	"Шаркс": "Sharks",
	"Ванкувер": "Vancouver",
	"Кэнакс": "Canucks",
	"Вегас": "Vegas",
	"Голден Найтс": "Golden Knights",

	"Какому клубу принадлежит логотип?": "Which of the clubs owns the logo?",
	"Статистика игры:": "Game statistics",
	"Вернуться к командам": "Back to the teams",
	"Играть снова": "Play again",
	"Следующий вопрос": "Next question",
	"Перейти к результатам": "Go to results",
	"Ваши результаты": "Your results",
	"Закрыть": "Close",
	"В процентах": "In percentages",
	"Верно": "Right",
	"Неверно": "Wrong",
};